os: linux
dist: xenial
sudo: false
cache:
  directories:
  # local::lib caching
  - $HOME/perl5
addons:
  apt:
    packages:
      - build-essential
      - ikiwiki
      - libtext-multimarkdown-perl
      - libimage-magick-perl
      - librsvg2-bin
      - cpanminus
      - libhighlight-perl
      - latexml
      - tex4ht
      - biber
      - texlive-bibtex-extra
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-pictures
      - graphviz
      #- tj3 # not latest version
      - dvipng # for teximg plugin
      - mupdf-tools # for mutool
install:
  - openssl aes-256-cbc -K $encrypted_4f43c47a058e_key -iv $encrypted_4f43c47a058e_iv -in .travisdeploykey.enc -out .travisdeploykey -d
  - chmod go-rwx .travisdeploykey
  - eval `ssh-agent -s`
  - ssh-add .travisdeploykey
  - git config --global push.default simple
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from
    `git log -n 1 --format='commit %h - %s'`"
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm -n YAML::Any YAML::XS Sort::Naturally LaTeXML
  - gem install taskjuggler

  # wrapper for `mutool` that calls `mudraw` since older version of
  # `mupdf-tools` had the draw subcommand separate
  #
  # Note: the \ \ EOF here-doc is due to Travis CI multi-line YAML inserting
  # two spaces.
  - |
    mkdir -p ~/bin
    cat <<\ \ EOF > ~/bin/mutool
    #!/bin/sh

    if [ "$1" = "draw" ]; then
      shift
      /usr/bin/mudraw "$@"
    else
      /usr/bin/mutool "$@"
    fi
    EOF
    chmod u+x ~/bin/mutool
    export PATH=$HOME/bin:$PATH
script:
  #- set -e
  - export PERL5LIB="$PERL5LIB:./.ikiwiki-plugins/rubykat-ikiplugins:./.ikiwiki-plugins/p5-IkiWiki-Plugin-github/lib:./.ikiwiki-plugins/p5-IkiWiki-Plugin-tex/lib:./.ikiwiki-plugins/p5-IkiWiki-Plugin-taskjuggler/lib:./.ikiwiki-plugins/ikiwiki-uml"
  - ikiwiki --rebuild --setup project-renard.setup --url 'http://project-renard.github.io/'
  - git clone --bare -b master git@github.com:project-renard/project-renard.github.io.git _site/.git
  - cd _site
  - git config core.bare false
  - git add -f .
  - 'git commit -m "${COMMIT_MESSAGE}" || true'
  - git push -f git@github.com:project-renard/project-renard.github.io.git master:master

branches:
  only:
    - source
